import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function SetTimeoutOne() {

  setTimeout(() => {
    console.log('Hello, World!')
  }, 3000);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Set Timeout One
      </main>
    </>
  )
}
